import { open, text, SCRATCH } from "./lib.mjs";
const { ctx, p } = await open();
await p.goto("http://localhost:3000/app/positions", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
await p.locator('a[href*="/app/position?v="]').first().click();
await p.waitForTimeout(3500);
console.log("TOP:", (await text(p, 900)).slice(130));
await p.screenshot({ path: `${SCRATCH}/f-closing.png` });
await p.getByRole("button", { name: "Close to USDT" }).first().click();
await p.waitForTimeout(800);
const modalBtn = p.getByRole("button", { name: /Close to USDT|Request close/ }).last();
console.log("modal button:", await modalBtn.textContent());
await modalBtn.click();
await p.waitForTimeout(6000);
console.log("AFTER:", (await text(p, 4000)).slice(-1400));
await p.screenshot({ path: `${SCRATCH}/f-closed.png` });
await ctx.close();
