import { open, text, SCRATCH } from "./lib.mjs";
const { ctx, p } = await open();
const label = process.argv[2] ?? "d";
await p.goto("http://localhost:3000/app/positions", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
console.log("LIST:", (await text(p, 1500)).slice(180, 900));
await p.locator('a[href*="/app/position?v="]').first().click();
await p.waitForTimeout(4000);
console.log("DETAIL:", (await text(p, 1200)).slice(130, 900));
await p.screenshot({ path: `${SCRATCH}/${label}-detail.png` });
await ctx.close();
