import { open, text, SCRATCH } from "./lib.mjs";
const { ctx, p } = await open();
await p.goto("http://localhost:3000/app/positions", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
await p.locator('a[href*="/app/position?v="]').first().click();
await p.waitForTimeout(3500);
await p.getByRole("button", { name: "Close to USDT" }).first().click();
await p.waitForTimeout(800);
console.log("MODAL:", (await text(p, 4000)).slice(-1800));
await p.screenshot({ path: `${SCRATCH}/e-modal.png` });
await p.getByRole("button", { name: /Request close|Close to USDT/ }).last().click();
await p.waitForTimeout(5000);
console.log("AFTER:", (await text(p, 4000)).slice(-1500));
await p.screenshot({ path: `${SCRATCH}/e-after-request.png` });
await ctx.close();
