import { open, text, SCRATCH } from "./lib.mjs";
const { ctx, p } = await open();
await p.goto("http://localhost:3000/app/positions", { waitUntil: "networkidle" });
await p.waitForTimeout(3000);
console.log(await text(p, 2000));
await p.screenshot({ path: `${SCRATCH}/b-list.png` });
const link = p.locator('a[href*="/app/position?v="]').first();
console.log("link count", await p.locator('a[href*="/app/position?v="]').count());
await link.click();
await p.waitForTimeout(4000);
console.log(p.url());
console.log(await text(p, 5000));
await p.screenshot({ path: `${SCRATCH}/b-detail.png`, fullPage: true });
await ctx.close();
