import { open, text } from "./lib.mjs";
const { ctx, p } = await open();
await p.goto("http://localhost:3000/app", { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
await p.locator("#amount").fill("55");
await p.getByRole("button", { name: /^Review/ }).click();
await p.waitForURL(/review/);
await p.waitForTimeout(2500);
console.log(await text(p, 3500));
await p.screenshot({ path: "/tmp/claude-1001/-home-hyprayush-Documents-Projects/02424c9d-833b-416a-9442-3d67076208de/scratchpad/review.png" });
await ctx.close();
