import { open, text } from "./lib.mjs";
const { ctx, p } = await open();
await p.goto("http://localhost:3000/app", { waitUntil: "networkidle" });
await p.getByRole("button", { name: "Connect wallet" }).first().click();
await p.waitForTimeout(500);
console.log(await text(p, 1200));
await p.getByText("Dev wallet").first().click();
await p.waitForTimeout(2500);
console.log("----after connect----\n" + (await text(p, 1500)));
await ctx.close();
