#!/usr/bin/env python3
"""Regenerate / check holidays/nyse_2026_2027.json (file name kept: deploy params, tests and SDK reference it).

  python3 holidays/gen_holidays.py          # rewrite the JSON
  python3 holidays/gen_holidays.py --check  # validate the JSON equals the rules and is sane (exit 1 on failure)

Rules: NYSE full closures (New Year's, MLK, Presidents, Good Friday, Memorial, Juneteenth, Independence, Labor,
Thanksgiving, Christmas). Saturday holiday -> observed Friday, except New Year's Day (no observance). Sunday -> Monday.
The contract has no half-day model, so early closes are listed as closures (EARLY). Window start 2026-09-07 matches the
launch; END is coversThroughDay. NYSE publishes only through 2028 (nyse.com/trade/hours-calendars), so END = 2028-12-31.
"""
import datetime as dt, json, os, sys

START, END = dt.date(2026, 9, 7), dt.date(2028, 12, 31)
EARLY = [dt.date(2026, 11, 27), dt.date(2026, 12, 24), dt.date(2027, 11, 26), dt.date(2028, 7, 3), dt.date(2028, 11, 24)]
PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nyse_2026_2027.json")
NOTE = ("Generated by gen_holidays.py. Sources: https://www.nyse.com/trade/hours-calendars and NYSE Group press release "
        "'2026, 2027 and 2028 Holiday and Early Closings Calendar' (2025-12-23, businesswire.com / ir.theice.com), checked 2026-10-04. "
        "Covers every NYSE full-day closure from 2026-09-07 through 2028-12-31. Early closes (1:00 p.m. ET: 2026-11-27, 2026-12-24, "
        "2027-11-26, 2028-07-03, 2028-11-24) are treated as full closures, which is the contract's model (no half-day). New Year's Day "
        "2028 (Saturday) has no observed holiday. 2029 is not published by NYSE yet, so coversThroughDay = 2028-12-31: the factory rejects a "
        "position with now + term + 14 days after this day (term_max = horizon - 14 days - now); extend the table and call "
        "setHolidayHorizon (guardian, no cap, no redeploy) before then. unixDays = unix seconds / 86400.")

def nth(y, m, wd, n):
    d = dt.date(y, m, 1); d += dt.timedelta((wd - d.weekday()) % 7)
    return d + dt.timedelta(7 * (n - 1))

def last(y, m, wd):
    d = dt.date(y, m + 1, 1) - dt.timedelta(1) if m < 12 else dt.date(y, 12, 31)
    return d - dt.timedelta((d.weekday() - wd) % 7)

def easter(y):
    a, b, c = y % 19, y // 100, y % 100; d, e = b // 4, b % 4; f = (b + 8) // 25; g = (b - f + 1) // 3
    h = (19 * a + b - d - g + 15) % 30; i, k = c // 4, c % 4; l = (32 + 2 * e + 2 * i - h - k) % 7
    m = (a + 11 * h + 22 * l) // 451; mo = (h + l - 7 * m + 114) // 31; da = (h + l - 7 * m + 114) % 31 + 1
    return dt.date(y, mo, da)

def observed(d):
    if d.weekday() == 5: return d - dt.timedelta(1)
    if d.weekday() == 6: return d + dt.timedelta(1)
    return d

def compute():
    out = set(EARLY)
    for y in range(2026, 2030):
        out |= {dt.date(y, 1, 1) if dt.date(y, 1, 1).weekday() != 5 else None}  # Sat Jan 1: nothing
        if dt.date(y, 1, 1).weekday() == 6: out.add(dt.date(y, 1, 2))
        out.discard(dt.date(y, 1, 1)) if dt.date(y, 1, 1).weekday() == 6 else None
        out |= {nth(y, 1, 0, 3), nth(y, 2, 0, 3), easter(y) - dt.timedelta(2), last(y, 5, 0), observed(dt.date(y, 6, 19)),
                observed(dt.date(y, 7, 4)), nth(y, 9, 0, 1), nth(y, 11, 3, 4), observed(dt.date(y, 12, 25))}
    out.discard(None)
    return sorted(d for d in out if START <= d <= END)

def build():
    ds = compute(); epoch = dt.date(1970, 1, 1)
    return {"_note": NOTE, "dates": [d.isoformat() for d in ds], "coversThroughDay": (END - epoch).days,
            "unixDays": [(d - epoch).days for d in ds]}

def validate(j):
    epoch = dt.date(1970, 1, 1); u = j["unixDays"]
    assert u == sorted(set(u)), "unsorted or duplicate"
    for n in u: assert (epoch + dt.timedelta(n)).weekday() < 5, f"weekend {epoch + dt.timedelta(n)}"
    assert [(epoch + dt.timedelta(n)).isoformat() for n in u] == j["dates"], "dates != unixDays"
    assert j["coversThroughDay"] >= u[-1] and j["coversThroughDay"] <= 30000

if __name__ == "__main__":
    j = build(); validate(j)
    if "--check" in sys.argv:
        cur = json.load(open(PATH)); validate(cur)
        if cur["unixDays"] != j["unixDays"] or cur["coversThroughDay"] != j["coversThroughDay"]:
            sys.exit("JSON differs from rules")
        print("ok", len(cur["unixDays"]), "days, horizon", (dt.date(1970, 1, 1) + dt.timedelta(cur["coversThroughDay"])))
    else:
        open(PATH, "w").write(json.dumps(j, indent=2) + "\n"); print("wrote", len(j["unixDays"]))
