// Regenerates src/abis/*.ts from Foundry output. Run: forge build (in packages/contracts) then `pnpm --filter @floor/sdk gen:abis`.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../../contracts/out');
const dest = resolve(here, '../src/abis');
mkdirSync(dest, { recursive: true });

const targets = [
  ['IFloorFactory', 'floorFactoryAbi'],
  ['IFloorVault', 'floorVaultAbi'],
  ['IFloorLens', 'floorLensAbi'],
  ['IPancakeV3SwapRouter', 'pancakeV3SwapRouterAbi'],
];

for (const [name, exportName] of targets) {
  const json = JSON.parse(readFileSync(`${out}/${name}.sol/${name}.json`, 'utf8'));
  const body = `// GENERATED by scripts/gen-abis.mjs from packages/contracts/out. Do not edit.\nexport const ${exportName} = ${JSON.stringify(json.abi, null, 2)} as const;\n`;
  writeFileSync(`${dest}/${name}.ts`, body);
  console.log(`wrote ${name}.ts (${json.abi.length} entries)`);
}
writeFileSync(
  `${dest}/index.ts`,
  `// GENERATED by scripts/gen-abis.mjs. Do not edit.\n${targets.map(([n, e]) => `export { ${e} } from './${n}';`).join('\n')}\n`,
);
