// GENERATED by scripts/gen-abis.mjs from packages/contracts/out. Do not edit.
export const floorLensAbi = [
  {
    "type": "function",
    "name": "scan",
    "inputs": [
      {
        "name": "from",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "to",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "needing",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "status",
    "inputs": [
      {
        "name": "vault",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IFloorLens.Status",
        "components": [
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "V",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "floor",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "cushion",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "exposure",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "target",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "needsRebalance",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "tradingOpen",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  }
] as const;
