#!/usr/bin/env python3
"""Floor v2 choreography: the keyframe table (the camera path is generated by comp.py from this table) and the
sound cue export.  `python3 choreo.py` writes v2/cues.json (and prints the table); `python3 choreo.py cut15` writes
v2/cues_cut15.json.

KEYFRAME TABLE (master, 30 fps, 1 beat = 20 frames).  One continuous camera path through a paper diorama.
Stations are flat paper planes (type cards 1920x1080 world units, UI panels 1440x900) 2850 units apart in depth and
+-2300 sideways, alternately yawed +-15..24 degrees.  Camera: pinhole f=2000 px, D=2180 (card) / 1900 (panel) face-on.
  a = frame the camera is settled face-on (+ slow hold drift of dyaw degrees until d)
  L = focus-lock frame (rack focus 16 px -> 0 finished; sharp for L..d, readability rule)
  d = departure: smootherstep move to the next station's arrival pose along an arc (orbit), until next a
 id  kind   a     L     d     yaw  note
 S0  card   0     14    146   0    cold open, floor line, lockup stamp 20, words 40/60/80, sub 100
 C1  card   172   186   219  -20   card-to-card join, arrives while words cut in at 160/180
 L1  panel  249   263   356  +18   landing scroll, dolly in, swing from yaw 18 to face-on
 C2  card   386   400   459  +22
 T1  panel  489   503   696  -17   slider follow (push in on the thumb), crash chips; D1=2250 slow pull-back
 C3  card   726   740   799  -22
 A1  panel  829   843   1076 +17   builder -> review -> confirmed, push-in follow on floor slider
 C4  card   1106  1120  1179 +24
 A2  panel  1209  1223  1316 -15
 C5  card   1346  1360  1419 -22
 G1  panel  1449  1463  1536 +18
 E1  card   1566  1580  1654 +20
 E2  card   1678  1692  1799  0    end card, lockup stamp 1720
"""
import json
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import comp
from engine import Cam

FPS = 30


def sec(n):
    return round(n / FPS, 4)


def cue(lst, kind, name, frame, **kw):
    d = dict(kind=kind, name=name, frame=int(frame), seconds=sec(frame))
    d.update(kw)
    lst.append(d)


def camera_stats(plan, rig, n0=0, n1=None):
    n1 = n1 or plan.frames
    P = []
    Q = []
    for n in range(n0, n1):
        c = rig.cam(n)
        P.append(c.pos)
        Q.append(c.yaw_pitch())
    P = np.array(P)
    V = np.diff(P, axis=0)
    A = np.diff(V, axis=0)
    return P, np.array(Q), V, A


def build(planname='master'):
    inp, plan, world, rig = comp.make_all(True) if planname == 'master' else comp.make_all_named(planname)
    cues = []
    st = {s.id: s for s in plan.st}
    # beats
    beats = list(range(0, plan.frames + 1, 20))
    # camera moves
    for sg in plan.seg:
        if sg['kind'] in ('hold', 'hold-drift'):
            if sg['n1'] - sg['n0'] > 20:
                cue(cues, 'camera', f"drift on {sg['to']}", sg['n0'], end_frame=sg['n1'], end_seconds=sec(sg['n1']),
                    move='hold-drift', station=sg['to'], intensity=0.15)
            continue
        dist = float(np.linalg.norm(sg['p1'] - sg['p0']))
        c0, c1 = rig.cam(sg['n0']), rig.cam(sg['n1'])
        cue(cues, 'camera', f"move to {sg['to']}", sg['n0'], end_frame=sg['n1'], end_seconds=sec(sg['n1']),
            move=sg['kind'], station=sg['to'], distance_units=round(dist), intensity=round(min(1.0, dist / 4000), 2),
            peak_frame=int((sg['n0'] + sg['n1']) / 2), yaw_start=round(c0.yaw_pitch()[0], 1),
            yaw_end=round(c1.yaw_pitch()[0], 1), direction='forward' if sg['p1'][2] < sg['p0'][2] else 'back',
            lateral='right' if sg['p1'][0] > sg['p0'][0] else 'left')
    # arrivals, focus lock, card arrivals
    for s in plan.st:
        cue(cues, 'arrival', f'{s.kind} {s.id} settled', s.a, station=s.id, plane=s.kind)
        cue(cues, 'focus_lock', f'{s.id} sharp', s.L, station=s.id, sharp_from=s.L, sharp_until=s.d,
            rack_start=max(0, s.a - 6), blur_start_px=comp.R0)
        cue(cues, 'defocus', f'{s.id} leaves focus', s.d, station=s.id)
    # word reveals
    for s in plan.st:
        if s.kind != 'card':
            continue
        ov = plan.typo_over
        for a in s.card['assets']:
            if plan.name != 'cut15' and 'cut15' in a['id']:
                continue
            if plan.name == 'cut15' and a['id'] + '_cut15' in [b['id'] for b in s.card['assets']]:
                continue
            o = ov.get(a['id'], {})
            if o.get('skip'):
                continue
            cue(cues, 'word_reveal', a['id'], o.get('in', a['in']), station=s.id, text=a.get('text', ''), role=a.get('role', ''))
        lk = s.card.get('lockup')
        if lk and not (ov.get('no_lockup') and s.id == 'S0') and not ov.get('S0_lockup', {}).get('skip') or (lk and s.id != 'S0'):
            cue(cues, 'stamp', f'lockup {s.id}', ov.get('lockup_in', lk.get('stamp_frame', 20)), station=s.id)
    # callout stickers
    for co in plan.callouts:
        c = next(x for x in inp.typo['callouts'] if x['id'] == co['id'])
        cue(cues, 'sticker_pop', co['id'], co['n_in'], text=c['text'], station=co['station'], color=c['sticker']['color'])
        cue(cues, 'sticker_text', co['id'] + ' text', co['n_in'] + 2)
        cue(cues, 'arrow', co['id'] + ' arrow', co['n_in'] + 20)
        cue(cues, 'sticker_out', co['id'], co['n_out'])
    for c in plan.captions:
        cue(cues, 'caption', c['id'], c['n_in'], end_frame=c['n_out'])
    # UI events from events.json mapped through each station's frame list
    for s in plan.st:
        if s.kind != 'panel':
            continue
        prev_floor = {}
        prev_down = {}
        scroll_prev = {}
        for i, (shot, k) in enumerate(s.frames):
            n = s.p0 + i
            fd = inp.ev(shot)['frames_data'][k]
            m = fd.get('mouse', {})
            dn = bool(m.get('down'))
            if dn and not prev_down.get(shot):
                cue(cues, 'ui_click_down', f'{shot} mouse down', n, shot=shot, capture_frame=k, x=m.get('x'), y=m.get('y'))
            if (not dn) and prev_down.get(shot):
                cue(cues, 'ui_click_up', f'{shot} mouse up', n, shot=shot, capture_frame=k)
            prev_down[shot] = dn
            if fd.get('click'):
                cue(cues, 'ui_click', f'{shot} click', n, shot=shot, capture_frame=k, x=m.get('x'), y=m.get('y'))
            fl = fd.get('floor')
            if fl is not None:
                if shot in prev_floor and fl != prev_floor[shot]:
                    cue(cues, 'slider_step', f'{shot} floor {prev_floor[shot]}->{fl}', n, shot=shot, capture_frame=k,
                        value=fl, delta=fl - prev_floor[shot])
                prev_floor[shot] = fl
            sy = fd.get('scrollY', 0)
            if shot in scroll_prev and abs(sy - scroll_prev[shot]) > 0.5:
                cue(cues, 'scroll', f'{shot} scroll', n, shot=shot, speed_px_per_frame=round(sy - scroll_prev[shot], 2))
            scroll_prev[shot] = sy
        # shot changes inside a station = chart swap / page change
        for i in range(1, len(s.frames)):
            if s.frames[i][0] != s.frames[i - 1][0]:
                cue(cues, 'page_change', f'{s.frames[i-1][0]} -> {s.frames[i][0]}', s.p0 + i, station=s.id)
    cues.sort(key=lambda c: (c['frame'], c['kind']))
    # compress scroll cues (keep every 3rd) to keep the file readable
    P, Q, V, A = camera_stats(plan, rig)
    out = dict(plan=planname, fps=FPS, frames=plan.frames, seconds=sec(plan.frames), bpm=90, beat_frames=20,
               beat_seconds=round(20 / 30, 4), beats=beats, bars_4_4_frames=list(range(0, plan.frames + 1, 80)),
               camera=dict(max_speed_units_per_frame=round(float(np.linalg.norm(V, axis=1).max()), 1),
                           max_accel_units_per_frame2=round(float(np.linalg.norm(A, axis=1).max()), 1)),
               stations=[dict(id=s.id, kind=s.kind, arrive=s.a, focus_lock=s.L, depart=s.d, yaw=s.yaw) for s in plan.st],
               cues=cues)
    return out


if __name__ == '__main__':
    name = sys.argv[1] if len(sys.argv) > 1 else 'master'
    o = build(name)
    fn = 'cues.json' if name == 'master' else f'cues_{name}.json'
    json.dump(o, open(os.path.join(HERE, fn), 'w'), indent=1)
    kinds = {}
    for c in o['cues']:
        kinds[c['kind']] = kinds.get(c['kind'], 0) + 1
    print(fn, len(o['cues']), kinds, o['camera'])
